### ISSUE TITLE
Multiple data folders

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/cellTracer#1]
The repository currently has two folders containing data: "[Example data](https://github.com/ocbe-uio/cellTracer/tree/master/Example%20Data)", containing a small text file, and "[data](https://github.com/ocbe-uio/cellTracer/tree/master/data)", containing three large TIFF files. Is that structrure OK or would all data be better organized into one folder?

**Comment by SystemsBiologist** [comment]
I think it is better to have one data folder which also contains the calculated tracks files ".mat"

**Comment by wleoncio** [comment]
Good idea. We might have to hold on and decide on where to store the TIFF files first, since they got rejected for surpassing the free tier data cap of 1 GB.

**Comment by SystemsBiologist** [comment]
What about in the worst case we keep one tiff file?

**Comment by wleoncio** [comment]
Works for me! :smile:

**Comment by SystemsBiologist** [comment]
Let us keep the "A3_2_Feb12.tif" then

**Comment by SystemsBiologist** [comment]
I spoke with Kamil yesterday, he will add the executable software ASAP

**Comment by SystemsBiologist** [comment]
Any news about DIscBIO?

**Comment by wleoncio** [comment]
> Let us keep the "A3_2_Feb12.tif" then

OK, will do.

> Any news about DIscBIO?

Just sent you a message on Teams a few minutes ago asking for instructions :wink:
